"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

# from __future__ import annotations
from enum import Enum

class AttemptFailureOriginEnum(str, Enum):
    r"""Indicates where the error originated. If not set, the origin of error is not well known."""
    SOURCE = 'source'
    DESTINATION = 'destination'
    REPLICATION = 'replication'
    PERSISTENCE = 'persistence'
    NORMALIZATION = 'normalization'
    DBT = 'dbt'
    AIRBYTE_PLATFORM = 'airbyte_platform'
    UNKNOWN = 'unknown'
