"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class AttemptStatusEnum(str, Enum):
    RUNNING = 'running'
    FAILED = 'failed'
    SUCCEEDED = 'succeeded'
