"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ConnectionStateTypeEnum(str, Enum):
    r"""Successful operation"""
    GLOBAL = 'global'
    STREAM = 'stream'
    LEGACY = 'legacy'
    NOT_SET = 'not_set'
