"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import streamstate as shared_streamstate
from airbyte import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Any, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class GlobalState:
    
    stream_states: list[shared_streamstate.StreamState] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('streamStates') }})
    shared_state: Optional[dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('shared_state'), 'exclude': lambda f: f is None }})
    