"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

# from __future__ import annotations
from enum import Enum

class JobTypeEnum(str, Enum):
    r"""enum that describes the different types of jobs that the platform runs."""
    GET_SPEC = 'get_spec'
    CHECK_CONNECTION = 'check_connection'
    DISCOVER_SCHEMA = 'discover_schema'
    SYNC = 'sync'
    RESET_CONNECTION = 'reset_connection'
    CONNECTION_UPDATER = 'connection_updater'
    REPLICATE = 'replicate'
