"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class NamespaceDefinitionTypeEnum(str, Enum):
    r"""Method used for computing final namespace in destination"""
    SOURCE = 'source'
    DESTINATION = 'destination'
    CUSTOMFORMAT = 'customformat'
