"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

# from __future__ import annotations
from enum import Enum

class NonBreakingChangesPreferenceEnum(str, Enum):
    IGNORE = 'ignore'
    DISABLE = 'disable'
