"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from airbyte import utils
from dataclasses_json import Undefined, dataclass_json


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OAuthConsentRead:
    r"""Successful operation"""
    
    consent_url: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('consentUrl') }})
    