"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

# from __future__ import annotations
import dataclasses
from airbyte import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OperatorWebhookDbtCloud:
    
    account_id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('accountId') }})
    r"""The account id associated with the job"""
    job_id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('jobId') }})
    r"""The job id associated with the job"""
    
class OperatorWebhookWebhookTypeEnum(str, Enum):
    DBT_CLOUD = 'dbtCloud'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OperatorWebhook:
    
    dbt_cloud: Optional[OperatorWebhookDbtCloud] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('dbtCloud'), 'exclude': lambda f: f is None }})
    execution_body: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('executionBody'), 'exclude': lambda f: f is None }})
    r"""DEPRECATED. Populate dbtCloud instead."""
    execution_url: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('executionUrl'), 'exclude': lambda f: f is None }})
    r"""DEPRECATED. Populate dbtCloud instead."""
    webhook_config_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('webhookConfigId'), 'exclude': lambda f: f is None }})
    r"""The id of the webhook configs to use from the workspace."""
    webhook_type: Optional[OperatorWebhookWebhookTypeEnum] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('webhookType'), 'exclude': lambda f: f is None }})
    