"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

# from __future__ import annotations
from enum import Enum

class ReleaseStageEnum(str, Enum):
    ALPHA = 'alpha'
    BETA = 'beta'
    GENERALLY_AVAILABLE = 'generally_available'
    CUSTOM = 'custom'
