"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class SchemaChangeEnum(str, Enum):
    NO_CHANGE = 'no_change'
    NON_BREAKING = 'non_breaking'
    BREAKING = 'breaking'
