"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

# from __future__ import annotations
import dataclasses
from ..shared import oauth2specification as shared_oauth2specification
from airbyte import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional

class SourceAuthSpecificationAuthTypeEnum(str, Enum):
    OAUTH2_0 = 'oauth2.0'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class SourceAuthSpecification:
    
    auth_type: Optional[SourceAuthSpecificationAuthTypeEnum] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('auth_type'), 'exclude': lambda f: f is None }})
    oauth2_specification: Optional[shared_oauth2specification.OAuth2Specification] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('oauth2Specification'), 'exclude': lambda f: f is None }})
    r"""An object containing any metadata needed to describe this connector's Oauth flow"""
    