"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class SyncModeEnum(str, Enum):
    FULL_REFRESH = 'full_refresh'
    INCREMENTAL = 'incremental'
