"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

# from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import healthcheckread as shared_healthcheckread
from typing import Optional


@dataclasses.dataclass
class GetHealthCheckResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    health_check_read: Optional[shared_healthcheckread.HealthCheckRead] = dataclasses.field(default=None)
    r"""Successful operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    