"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import internaloperationresult as shared_internaloperationresult
from typing import Optional


@dataclasses.dataclass
class SaveSyncConfigResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    internal_operation_result: Optional[shared_internaloperationresult.InternalOperationResult] = dataclasses.field(default=None)
    r"""Successful Operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    