"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import connectionreadlist as shared_connectionreadlist
from ..shared import invalidinputexceptioninfo as shared_invalidinputexceptioninfo
from typing import Optional


@dataclasses.dataclass
class SearchConnectionsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    connection_read_list: Optional[shared_connectionreadlist.ConnectionReadList] = dataclasses.field(default=None)
    r"""Successful operation"""
    invalid_input_exception_info: Optional[shared_invalidinputexceptioninfo.InvalidInputExceptionInfo] = dataclasses.field(default=None)
    r"""Input failed validation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    