"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import knownexceptioninfo as shared_knownexceptioninfo
from ..shared import notfoundknownexceptioninfo as shared_notfoundknownexceptioninfo
from typing import Optional


@dataclasses.dataclass
class SetInstancewideDestinationOauthParamsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    known_exception_info: Optional[shared_knownexceptioninfo.KnownExceptionInfo] = dataclasses.field(default=None)
    r"""Exception occurred; see message for details."""
    not_found_known_exception_info: Optional[shared_notfoundknownexceptioninfo.NotFoundKnownExceptionInfo] = dataclasses.field(default=None)
    r"""Object with given id was not found."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    