"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import webbackendcheckupdatesread as shared_webbackendcheckupdatesread
from typing import Optional


@dataclasses.dataclass
class WebBackendCheckUpdatesResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    web_backend_check_updates_read: Optional[shared_webbackendcheckupdatesread.WebBackendCheckUpdatesRead] = dataclasses.field(default=None)
    r"""Successful operation"""
    