"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

# from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import webbackendgeographieslistresult as shared_webbackendgeographieslistresult
from typing import Optional


@dataclasses.dataclass
class WebBackendListGeographiesResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    web_backend_geographies_list_result: Optional[shared_webbackendgeographieslistresult.WebBackendGeographiesListResult] = dataclasses.field(default=None)
    r"""Successful operation"""
    