"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import discovercatalogresult as shared_discovercatalogresult
from typing import Optional


@dataclasses.dataclass
class WriteDiscoverCatalogResultResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    discover_catalog_result: Optional[shared_discovercatalogresult.DiscoverCatalogResult] = dataclasses.field(default=None)
    r"""Successful Operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    